name: "Scheduled Run"

on:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18    
      - run: cd scheduled && npm i && node main.js
        env:
          URL: ${{ secrets.URL }}
          APP_KEY: ${{ secrets.APP_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
