name: hourly-cron-job
on: [workflow_dispatch]
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      URL: '${{ secrets.Production.URL }}'
      APP_KEY: '${{ secrets.Production.APP_KEY }}'
      OPENAI_API_KEY: '${{ secrets.Production.OPENAI_API_KEY }}'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: cd scheduled && npm i && node main.js
